ARG JOBS_IMAGE

FROM $JOBS_IMAGE

RUN apk add --no-cache \
      g++ \
      git \
      make \
      python

USER nodejs

VOLUME ["/opt/app/dft-street-manager-jobs"]

WORKDIR /opt/app/dft-street-manager-jobs

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["sh", "-c",  "npm set progress=false && npm config set depth 0 && npm install && npm run build && npm run start"]

