version: "3.3"
services:
  postgres:
    image: 454455319752.dkr.ecr.eu-west-2.amazonaws.com/postgres:postgres-10.11-r5
    ports:
      - "5432:5432"
  jobs:
    image: ${ECR_URL}/jobs:${CIRCLE_SHA1}
    depends_on:
      - db-migrations
    environment:
      - PGHOST=postgres
      - PGDATABASE=work
      - PGUSER=app
      - PGPASSWORD=app
  db-migrations:
    image: ${ECR_URL}/db-migrations:${DB_MIGRATIONS_IMAGE}
    volumes:
      - ~/project/clone/resources:/tmp/resources
    command: |
      sh -c 'apk add --no-cache postgresql-client && sh /tmp/resources/wait-for-postgres -- npm run migrations && psql -f /tmp/resources/insert-users.sql'
    depends_on:
      - postgres
    environment:
      - PGHOST=postgres
      - PGDATABASE=work
      - PGUSER=migrator
      - PGPASSWORD=migrator
      - PGKNEXUSER=migrator
      - PGKNEXPASSWORD=migrator
volumes:
  etc_postgresql:
    driver: local
  var_log_postgresql:
    driver: local
  var_lib_postgresql:
    driver: local
