version: "3.3"
services:
  postgres:
    image: ${ECR_URL}/postgres:postgres-10.15-r1
    ports:
      - "${PGPORT}:${PGPORT}"
  jobs:
    image: ${ECR_URL}/jobs:${CIRCLE_SHA1}
    depends_on:
      - db-migrations
    environment:
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGAPPUSER}
      - PGPASSWORD=${PGAPPPASSWORD}
  db-migrations:
    image: ${ECR_URL}/db-migrations:${DB_MIGRATIONS_IMAGE}
    volumes:
      - ~/project/clone/resources:/tmp/resources
    command: |
      sh -c 'apk add --no-cache postgresql-client && sh /tmp/resources/wait-for-postgres -- npm run migrations && psql -f /tmp/resources/insert-users.sql'
    depends_on:
      - postgres
    environment:
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGKNEXUSER=${PGKNEXUSER}
      - PGKNEXPASSWORD=${PGKNEXPASSWORD}
volumes:
  etc_postgresql:
    driver: local
  var_log_postgresql:
    driver: local
  var_lib_postgresql:
    driver: local
